channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - psutil==5.8.0
  - scikit-learn==0.24.2
  - typing-extensions==3.10.0.2
name: mlflow-env
